spring:
  datasource:
        url: jdbc:mysql://localhost:3306/batchdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: batch
        password: batch1234
        driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console

  sql:
    init:
      mode: always

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always